### ISSUE TITLE
Completely insecure in its current form

### ISSUE THREAD

**Issue by danielchatfield** [docker-library/sentry#5]
This image has hardcoded secret keys with no way to change them, what is the point on having "official images" if they don't even have the most cursory of checks done on them.

It is impossible to securely configure this image.

**Comment by tianon** [comment]
"Impossible" is a little bit over the top, don't you think?  It's pretty easy to inject your own configuration file, and I'd highly recommend it.

In fact, I think that'd be a pretty good solution to both #2 and #4 (making this image more like haproxy and requiring users to bring their own configuration and documenting how to generate one, since it's relatively easy to do).

What do you think, @yosifkit?

**Comment by yosifkit** [comment]
That seems valid, but there is the option of going like the wordpress image and either taking them in as an env or generating one on the first start.

**Comment by danielchatfield** [comment]
Ok, its not "impossible" - you can just create your own image for example.

@yosifkit that sounds sensible

**Comment by Starefossen** [comment]
@danielchatfield you are talking about the `SECRET_KEY` right?

**Comment by danielchatfield** [comment]
Yes
